# Generated by Django 5.2.5 on 2025-08-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_users', '0002_alter_todo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
