# Generated by Django 5.2.5 on 2025-08-13 08:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_users', '0003_alter_todo_description_alter_todo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(default='Moyenne', max_length=50),
        ),
        migrations.AlterField(
            model_name='projet',
            name='member_project',
            field=models.ManyToManyField(blank=True, to='manage_users.membre'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_users.membre'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='project_as',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_users.projet'),
        ),
    ]
