# Generated by Django 5.2.5 on 2025-08-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_users', '0004_todo_priority_alter_projet_member_project_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membre',
            options={'verbose_name': 'Membre', 'verbose_name_plural': 'Membres'},
        ),
        migrations.RemoveField(
            model_name='membre',
            name='member_name',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='last_name',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='poste',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin / Chef de projet'), ('membre_simple', 'Membre simple')], default='membre_simple', max_length=20),
        ),
    ]
